[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "azure.eventhub"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Data Ingestion", "Cost/Paid", "Vendor/Microsoft", "Area/Cloud & Infrastructure", "Type/Connector", "Name/Azure Event Hubs"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.eventhub"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
