[package]
org = "ballerinax"
name = "azure_eventhub"
version = "1.0.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["azure","eventhub","events","data ingestion"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.eventhub"
